site_name: Jane docs
site_description: Process guides, tutorials, and reference information for using Jane in modern projects.
site_url: 'https://steven-clements.github.io/jane'

theme: material

plugins:
  - search

nav:
  - Meet Jane: index.md
  - Reference:
    - Overview: reference/overview.md
    - Types:
      - Overview: reference/types/index.md
      - ValidationResult: reference/types/validation-result.md
    - Type guards:
      - Overview: reference/type-guards/index.md
      - Primitives:
        - Overview: reference/type-guards/primitives/index.md
        - isBigInteger: reference/type-guards/primitives/is-big-integer.md
        - isBoolean: reference/type-guards/primitives/is-boolean.md
        - isFiniteNumber: reference/type-guards/primitives/is-finite-number.md
        - isInteger: reference/type-guards/primitives/is-integer.md
        - isNegativeInteger: reference/type-guards/primitives/is-negative-integer.md
        - isNegativeNumber: reference/type-guards/primitives/is-negative-number.md
        - isNonEmptyString: reference/type-guards/primitives/is-non-empty-string.md
        - isNonNegativeInteger: reference/type-guards/primitives/is-non-negative-integer.md
        - isNonNegativeNumber: reference/type-guards/primitives/is-non-negative-number.md
        - isNull: reference/type-guards/primitives/is-null.md
        - isNullOrUndefined: reference/type-guards/primitives/is-null-or-undefined.md
        - isNumber: reference/type-guards/primitives/is-number.md
        - isPositiveInteger: reference/type-guards/primitives/is-positive-integer.md
        - isPositiveNumber: reference/type-guards/primitives/is-positive-number.md
        - isSafeInteger: reference/type-guards/primitives/is-safe-integer.md
        - isString: reference/type-guards/primitives/is-string.md
        - isSymbol: reference/type-guards/primitives/is-symbol.md
        - isUndefined: reference/type-guards/primitives/is-undefined.md
      - Structural:
        - Overview: reference/type-guards/structural/index.md
        - isArray: reference/type-guards/structural/is-array.md
        - isNonEmptyArray: reference/type-guards/structural/is-non-empty-array.md
        - isObject: reference/type-guards/structural/is-object.md
        - isPlainObject: reference/type-guards/structural/is-plain-object.md
        - isRecord: reference/type-guards/structural/is-record.md
        - isTuple: reference/type-guards/structural/is-tuple.md
      - Collections:
        - Overview: reference/type-guards/collections/index.md
        - isMap: reference/type-guards/collections/is-map.md
        - isSet: reference/type-guards/collections/is-set.md
        - isTypedArray: reference/type-guards/collections/is-typed-array.md
        - isWeakMap: reference/type-guards/collections/is-weak-map.md
        - isWeakSet: reference/type-guards/collections/is-weak-set.md
      - Semantic:
        - Overview: reference/type-guards/semantic/index.md
        - isDate: reference/type-guards/semantic/is-date.md
        - isEnumValue: reference/type-guards/semantic/is-enum-value.md
        - isError: reference/type-guards/semantic/is-error.md
        - isFunction: reference/type-guards/semantic/is-function.md
        - isJSON: reference/type-guards/semantic/is-json.md
        - isPort: reference/type-guards/semantic/is-port.md
        - isRegExp: reference/type-guards/semantic/is-reg-exp.md
        - isTimestamp: reference/type-guards/semantic/is-timestamp.md
      - Protocols:
        - Overview: reference/type-guards/protocols/index.md
        - isAsyncIterable: reference/type-guards/protocols/is-async-iterable.md
        - isIterable: reference/type-guards/protocols/is-iterable.md
        - isPromise: reference/type-guards/protocols/is-promise.md
    - Normalizers:
      - Overview: reference/normalizers/index.md
      - Primitives:
        - Overview: reference/normalizers/primitives/index.md
        - normalizeBoolean: reference/normalizers/primitives/normalize-boolean.md
        - normalizeFiniteNumber: reference/normalizers/primitives/normalize-finite-number.md
        - normalizeInteger: reference/normalizers/primitives/normalize-integer.md
        - normalizeNegativeInteger: reference/normalizers/primitives/normalize-negative-integer.md
        - normalizeNegativeNumber: reference/normalizers/primitives/normalize-negative-number.md
        - normalizeNonEmptyString: reference/normalizers/primitives/normalize-non-empty-string.md
        - normalizeNonNegativeInteger: reference/normalizers/primitives/normalize-non-negative-integer.md
        - normalizeNonNegativeNumber: reference/normalizers/primitives/normalize-non-negative-number.md
        - normalizeNumber: reference/normalizers/primitives/normalize-number.md
        - normalizePositiveInteger: reference/normalizers/primitives/normalize-positive-integer.md
        - normalizePositiveNumber: reference/normalizers/primitives/normalize-positive-number.md
        - normalizeSafeInteger: reference/normalizers/primitives/normalize-safe-integer.md
        - normalizeString: reference/normalizers/primitives/normalize-string.md
      - Structural:
        - Overview: reference/normalizers/structural/index.md
        - normalizePlainObject: reference/normalizers/structural/normalize-plain-object.md
        - normalizeRecord: reference/normalizers/structural/normalize-record.md
      - Semantic:
        - Overview: reference/normalizers/semantic/index.md
        - normalizeJSON: reference/normalizers/semantic/normalize-json.md
        - normalizePort: reference/normalizers/semantic/normalize-port.md
        - normalizeTimestamp: reference/normalizers/semantic/normalize-timestamp.md
      - Protocols:
        - Overview: reference/normalizers/protocols/index.md
        - normalizeAsyncIterable: reference/normalizers/protocols/normalize-async-iterable.md
        - normalizeIterable: reference/normalizers/protocols/normalize-iterable.md
        - normalizePromise: reference/normalizers/protocols/normalize-promise.md
    - Validators:
      - Overview: reference/validators/index.md
      - Primitives:
        - Overview: reference/validators/primitives/index.md
        - validateBigInteger: reference/validators/primitives/validate-big-integer.md
        - validateBoolean: reference/validators/primitives/validate-boolean.md
        - validateFiniteNumber: reference/validators/primitives/validate-finite-number.md
        - validateInteger: reference/validators/primitives/validate-integer.md
        - validateNegativeInteger: reference/validators/primitives/validate-negative-integer.md
        - validateNegativeNumber: reference/validators/primitives/validate-negative-number.md
        - validateNonEmptyString: reference/validators/primitives/validate-non-empty-string.md
        - validateNonNegativeInteger: reference/validators/primitives/validate-non-negative-integer.md
        - validateNonNegativeNumber: reference/validators/primitives/validate-non-negative-number.md
        - validateNull: reference/validators/primitives/validate-null.md
        - validateNumber: reference/validators/primitives/validate-number.md
        - validatePositiveInteger: reference/validators/primitives/validate-positive-integer.md
        - validatePositiveNumber: reference/validators/primitives/validate-positive-number.md
        - validateSafeInteger: reference/validators/primitives/validate-safe-integer.md
        - validateString: reference/validators/primitives/validate-string.md
        - validateSymbol: reference/validators/primitives/validate-symbol.md
        - validateUndefined: reference/validators/primitives/validate-undefined.md
      - Structural:
        - Overview: reference/validators/structural/index.md
        - validateArray: reference/validators/structural/validate-array.md
        - validateNonEmptyArray: reference/validators/structural/validate-non-empty-array.md
        - validateObject: reference/validators/structural/validate-object.md
        - validatePlainObject: reference/validators/structural/validate-plain-object.md
        - validateRecord: reference/validators/structural/validate-record.md
        - validateTuple: reference/validators/structural/validate-tuple.md
      - Collections:
        - Overview: reference/validators/collections/index.md
      - Semantic:
        - Overview: reference/validators/semantic/index.md
      - Protocols:
        - Overview: reference/validators/protocols/index.md
  - Contributing:
    - Overview: contributing/overview.md
    - Development workflow: contributing/development-workflow.md
    - Restricted repo files: contributing/restricted-repo-files.md
