site_name: Jane docs
site_description: Process guides, tutorials, and reference information for using Jane in modern projects.
site_url: 'https://steven-clements.github.io/jane'

theme: material
exclude:
  - virtual/*

nav:
  - Meet Jane: index.md
  - Reference:
    - Overview: reference/overview.md
    - Type guards:
      - Overview: reference/guards/index.md
      - isInteger: reference/guards/is-integer.md
      - isNonEmptyString: reference/guards/is-non-empty-string.md
      - isNumber: reference/guards/is-number.md
      - isString: reference/guards/is-string.md
  - Contributing:
    - Overview: contributing/index.md
    - Development workflow: contributing/development-workflow.md
    - Restricted repo files: contributing/restricted-repo-files.md
  - Changelog: ../CHANGELOG.md
