site_name: Jane docs
site_description: Process guides, tutorials, and reference information for using Jane in modern projects.
site_url: 'https://steven-clements.github.io/jane'

theme: material
exclude:
  - virtual/*

nav:
  - Meet Jane: index.md
  - Reference:
    - Overview: reference/overview.md
    # - Normalizers:
    #   - Overview: reference/normalize/index.md
    #   - normalizeArray: reference/normalize/normalize-array.md
    #   - normalizeBoolean: reference/normalize/normalize-boolean.md
    #   - normalizeDate: reference/normalize/normalize-date.md
    #   - normalizeEnumValue: reference/normalize/normalize-enum-value.md
    #   - normalizeInteger: reference/normalize/normalize-integer.md
    #   - normalizeNonEmptyString: reference/normalize/normalize-non-empty-string.md
    #   - normalizeNumber: reference/normalize/normalize-string.md
    #   - normalizeObject: reference/normalize/normalize-object.md
    #   - normalizePlainObject: reference/normalize/normalize-plain-object.md
    #   - normalizePort: reference/normalize-port.md
    #   - normalizePromise: reference/normalize-promise.md
    #   - normalizeRecord: reference/normalize-record.md
    #   - normalizeString: reference/normalize/normalize-string.md
    #   - normalizeTimestamp: reference/normalize/normalize-timestamp.md
    - Type guards:
      - Overview: reference/guard/index.md
      - isArray: reference/guard/is-array.md
      - isBoolean: reference/guard/is-boolean.md
      - isDate: reference/guard/is-date.md
      - isEnumValue: reference/guard/is-enum-value.md
      - isFunction: reference/guard/is-function.md
      - isInteger: reference/guard/is-integer.md
      - isNonEmptyString: reference/guard/is-non-empty-string.md
      - isNumber: reference/guard/is-number.md
      - isObject: reference/guard/is-object.md
      - isPlainObject: reference/guard/is-plain-object.md
      - isPort: reference/guard/is-port.md
      - isPromise: reference/guard/is-promise.md
      - isRecord: reference/guard/is-record.md
      - isString: reference/guard/is-string.md
      - isTimestamp: reference/guard/is-timestamp.md
  - Contributing:
    - Overview: contributing/index.md
    - Development workflow: contributing/development-workflow.md
    - Restricted repo files: contributing/restricted-repo-files.md
  - Changelog: ../CHANGELOG.md
